version: '3.2'

services:

  moodle-nginx:
    build: ./nginx
    restart: always
    ports:
      - 80:80
    volumes: 
      - "./nginx/conf.d/:/etc/nginx/conf.d/"
      - "./apps/moodle:/usr/share/nginx"
    depends_on: 
      - moodle-fpm

  moodle-fpm:
    build: ./php-fpm
    restart: always
    volumes: 
      - "./php-fpm/pool.d/:/etc/php/7.4/fpm/pool.d/"
      - "./apps/moodle:/usr/share/nginx"
      - "./apps/moodledata:/usr/share/moodledata"
    depends_on: 
      - moodle-db

  moodle-db: 
    image: postgres
    restart: always
    volumes: 
      - ./apps/postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${MOODLE_DB_ROOT_PASSWORD}
      PGDATA: /var/lib/postgresql/data/moodle