version: '3.2'

services:
  proxy:
    build: ./nginx
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes: 
      - "./nginx/proxy/nginx.conf:/etc/nginx/nginx.conf"
      - "./nginx/proxy/conf.d/:/etc/nginx/conf.d/"
      - "./apps/letsencrypt/:/etc/letsencrypt"
    depends_on: 
      - moodle-nginx
      - wordpress-nginx
      - nextcloud-nginx
      - strapi-node 

  moodle-nginx:
    build: ./nginx
    restart: always
    volumes: 
      - "./nginx/moodle/nginx.conf:/etc/nginx/nginx.conf"
      - "./nginx/moodle/conf.d/:/etc/nginx/conf.d/"
      - "./apps/moodle:/usr/share/nginx"
    depends_on: 
      - moodle-fpm

  moodle-fpm:
    build: ./php-fpm
    restart: always
    volumes: 
      - "./php-fpm/pool.d/:/etc/php/7.4/fpm/pool.d/"
      - "./apps/moodle:/usr/share/nginx"
      - "./apps/moodledata:/usr/share/moodledata"
    depends_on: 
      - moodle-db

  moodle-db: 
    image: postgres
    restart: always
    volumes: 
      - ./apps/postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${MOODLE_DB_ROOT_PASSWORD}
      PGDATA: /var/lib/postgresql/data/moodle

  nextcloud-nginx:
    build: ./nginx
    restart: always
    volumes: 
      - "./nginx/nextcloud/nginx.conf:/etc/nginx/nginx.conf"
      - "./nginx/nextcloud/conf.d/:/etc/nginx/conf.d/"
      - "./apps/nextcloud:/usr/share/nginx"
    depends_on: 
      - nextcloud-fpm

  nextcloud-fpm:
    build: ./php-fpm
    restart: always
    volumes: 
      - "./php-fpm/pool.d/:/etc/php/7.4/fpm/pool.d/"
      - "./apps/nextcloud:/usr/share/nginx"
      # - "./apps/moodledata:/usr/share/moodledata"
    depends_on: 
      - nextcloud-db

  nextcloud-db: 
    image: mariadb
    restart: always
    volumes: 
      - ./apps/mariadb:/var/lib/mysql 
    environment:
      MYSQL_ROOT_PASSWORD: ${NEXTCLOUD_DB_ROOT_PASSWORD}

  wordpress-nginx:
    build: ./nginx
    restart: always
    volumes: 
      - "./nginx/wordpress/nginx.conf:/etc/nginx/nginx.conf"
      - "./nginx/wordpress/conf.d/:/etc/nginx/conf.d/"
      - "./apps/wordpress:/usr/share/nginx"
    depends_on: 
      - wordpress-fpm

  wordpress-fpm:
    build: ./php-fpm
    restart: always
    volumes: 
      - "./php-fpm/pool.d/:/etc/php/7.4/fpm/pool.d/"
      - "./apps/wordpress:/usr/share/nginx"
      # - "./apps/wordpress:/usr/share/wordpress"
    depends_on: 
      - wordpress-db

  wordpress-db: 
    image: mysql
    restart: always
    volumes: 
      - ./apps/mysql:/var/lib/mysql 
    environment:
      MYSQL_ROOT_PASSWORD: ${WORDPRESS_DB_ROOT_PASSWORD}


  strapi-node:
    build: ./node
    volumes:
      - ./apps/strapi:/usr/src/app
    restart: always
    depends_on: 
      - wordpress-db

  strapi-db:
    image: mongo
    restart: always
    volumes:
      - "./apps/mongodata:/data/db"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_DB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_DB_ROOT_PASSWORD}
